Bootstrap: docker
From: quay.io/biocontainers/sra-tools%3A2.10.9--pl526haddd2b5_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://gitlab.psc.edu/icaoberg/singularity-sra-toolkit
    VERSION 2.10.9

%post
   rm /etc/resolv.conf

####################################################################################
